#!/bin/bash
set -e
hugo
rsync -avz -e 'ssh -oHostKeyAlgorithms=+ssh-dss' --exclude build --exclude lean_packages --exclude "*~" public/ math.iisc.ac.in:/home/gadgil/public_html/proofs-and-programs-2023/
