#!/bin/bash
set -e
lake -Kdoc=on build PnP2023:docs
cp -R build/doc static/
hugo
rsync -avz -e 'ssh -oHostKeyAlgorithms=+ssh-dss' --exclude build --exclude lean_packages --exclude "*~" public/ math.iisc.ac.in:/home/gadgil/public_html/proofs-and-programs-2023/
